#ifndef GZPARALLELGRIPPERPLUGINSHARED_GLOBAL_H
#define GZPARALLELGRIPPERPLUGINSHARED_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(GZPARALLELGRIPPERPLUGIN_LIBRARY)
//#  define GZJNTCMDPLUGINSHARED_EXPORT Q_DECL_EXPORT
#  define GZPARALLELGRIPPERPLUGINSHARED_EXPORT
#else
#  define GZPARALLELGRIPPERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GZPARALLELGRIPPERPLUGINSHARED_GLOBAL_H
