// Generated by gencpp from file crcl_rosmsgs/CrclStatusMsg.msg
// DO NOT EDIT!


#ifndef CRCL_ROSMSGS_MESSAGE_CRCLSTATUSMSG_H
#define CRCL_ROSMSGS_MESSAGE_CRCLSTATUSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <sensor_msgs/JointState.h>

namespace crcl_rosmsgs
{
template <class ContainerAllocator>
struct CrclStatusMsg_
{
  typedef CrclStatusMsg_<ContainerAllocator> Type;

  CrclStatusMsg_()
    : header()
    , crclcommandnum(0)
    , crclstatusnum(0)
    , crclcommandstatus(0)
    , statuspose()
    , statusjoints()
    , eepercent(0.0)  {
    }
  CrclStatusMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , crclcommandnum(0)
    , crclstatusnum(0)
    , crclcommandstatus(0)
    , statuspose(_alloc)
    , statusjoints(_alloc)
    , eepercent(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _crclcommandnum_type;
  _crclcommandnum_type crclcommandnum;

   typedef uint8_t _crclstatusnum_type;
  _crclstatusnum_type crclstatusnum;

   typedef uint8_t _crclcommandstatus_type;
  _crclcommandstatus_type crclcommandstatus;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _statuspose_type;
  _statuspose_type statuspose;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _statusjoints_type;
  _statusjoints_type statusjoints;

   typedef double _eepercent_type;
  _eepercent_type eepercent;



  enum {
    done = 0u,
    error = 1u,
    working = 2u,
  };


  typedef boost::shared_ptr< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> const> ConstPtr;

}; // struct CrclStatusMsg_

typedef ::crcl_rosmsgs::CrclStatusMsg_<std::allocator<void> > CrclStatusMsg;

typedef boost::shared_ptr< ::crcl_rosmsgs::CrclStatusMsg > CrclStatusMsgPtr;
typedef boost::shared_ptr< ::crcl_rosmsgs::CrclStatusMsg const> CrclStatusMsgConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crcl_rosmsgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'crcl_rosmsgs': ['/home/michalos/src/gzaprsros-xenial/src/crcl/crcl_rosmsgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a181126e6f9d61626d59419a96f05724";
  }

  static const char* value(const ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa181126e6f9d6162ULL;
  static const uint64_t static_value2 = 0x6d59419a96f05724ULL;
};

template<class ContainerAllocator>
struct DataType< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crcl_rosmsgs/CrclStatusMsg";
  }

  static const char* value(const ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CrclStatusMsg.msg\n\
# Crcl status contains information for canonical robot command language exchange.\n\
# CRCL is expressed in XML.\n\
# At a primite level, a CRCL message is a framed xml string.\n\
# So, the ROS status message contains a xml string and the originating ip from where the CRCL message came.\n\
# https://github.com/ros/common_msgs \n\
\n\
\n\
std_msgs/Header header\n\
\n\
uint8 crclcommandnum\n\
uint8 crclstatusnum\n\
uint8 crclcommandstatus\n\
################\n\
uint8 done=0\n\
uint8 error=1\n\
uint8 working=2\n\
################\n\
\n\
geometry_msgs/Pose  statuspose\n\
sensor_msgs/JointState statusjoints\n\
float64 eepercent\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
";
  }

  static const char* value(const ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.crclcommandnum);
      stream.next(m.crclstatusnum);
      stream.next(m.crclcommandstatus);
      stream.next(m.statuspose);
      stream.next(m.statusjoints);
      stream.next(m.eepercent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CrclStatusMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crcl_rosmsgs::CrclStatusMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "crclcommandnum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crclcommandnum);
    s << indent << "crclstatusnum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crclstatusnum);
    s << indent << "crclcommandstatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crclcommandstatus);
    s << indent << "statuspose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.statuspose);
    s << indent << "statusjoints: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.statusjoints);
    s << indent << "eepercent: ";
    Printer<double>::stream(s, indent + "  ", v.eepercent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRCL_ROSMSGS_MESSAGE_CRCLSTATUSMSG_H
